behaviors:
  RectAgentAO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.90
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 10000000  # Previous experiments used 10 million
    time_horizon: 100
    summary_freq: 4096
env_settings:
  env_path: ./builds/aaaa/audio.x86_64
  env_args: ["-agent", "rectAO", "-decisionperiod", "1", "-losreward", "0", "-targetspeed", "0"]
  base_port: 5205
  num_envs: 20
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  time_scale: 1
  target_frame_rate: 50
  capture_frame_rate: 50
  no_graphics: true
